python InstMag_Bmag_aperture_annulus_r_file_median_w1_subplot_date_FU_Ori_ABE.py
python InstMag_Vmag_aperture_annulus_r_file_median_w1_subplot_date_FU_Ori_ABE.py
python InstMag_Rmag_aperture_annulus_r_file_median_w1_subplot_date_FU_Ori_ABE.py
