python slt_InstMag_Bmag_aperture_annulus_r_file_median_w1_subplot_date_FU_Ori_ABDE.py
python slt_InstMag_Vmag_aperture_annulus_r_file_median_w1_subplot_date_FU_Ori_ABDE.py
python slt_InstMag_Rmag_aperture_annulus_r_file_median_w1_subplot_date_FU_Ori_ABDE.py
